[project]
name = "sale-fish-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10,<3.13"
dependencies = [
    "environs>=14.6.0",
    "python-telegram-bot==13.15",
    "redis>=7.2.1",
    "requests>=2.32.5",
    "setuptools>=68,<81",
    "urllib3<2",
]
[tool.ruff.lint.isort]
lines-after-imports = 2
